version: '3'

services:
  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    # restart: always
    ports:
    - "27017:27017"
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=paxxword
    # - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
    # - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
    - ./mongo-seed/:/docker-entrypoint-initdb.d/

  mongo_backup:
    container_name: mongo_backup
    build: ./mongo-backup
    # restart: always
    links:
    - mongo_db
    environment:
    - BCK2GIT_INSTANCE_NAME=test
    - BCK2GIT_MONGO_HOST=mongo_db
    - BCK2GIT_MONGO_PORT=27017
    - BCK2GIT_MONGO_USERNAME=root
    - BCK2GIT_MONGO_PASSWORD=paxxword
    - BCK2GIT_SCHEDULE=*/1 * * * *
    - BCK2GIT_GIT_URL=git@github.com:twittwer/database-backup.git
    - BCK2GIT_GIT_NAME
    volumes:
    - ~/.ssh/id_rsa:/data/ssh_private_key
